# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: course-service
  datasource:
    url: jdbc:postgresql://localhost:5432/coursedb
    username: user
    password: user123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true
 
#Register as Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka      
  instance:
       ip-address: 127.0.0.1
       preferIpAddress: true
       hostname: localhost
      
#Accuator SetUp
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    
  info:
    env:
      enabled: true
      
      

    
#Info Setup Under accuator
info:
  app:
    name: "course-service-dev-from-git-server-made-changes-latest"
    description: "This is Course Service"
    version: 1.0
server:
  port: 9092


#Setting up Circuit breaker Resilience4j
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 1000
    instances:
      myCourseServiceCircuitBreaker:
        baseConfig: default
      myCourseServiceCircuitBreakerWC:
        baseConfig: default
#Set Logger 
logging:
 level:
   root: INFO
