server:
  port: 9093
spring:
  application:
    name: video-service

  data:
    mongodb:
      host: localhost
      port: 27018
      database: videodb
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest


      
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
  instance:
       ip-address: 127.0.0.1
       preferIpAddress: true
       hostname: localhost
      

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
      
      
info:
  app:
    name: "video-service-from-git-server-latest"
    description:  "This is video service"
    version: "1.2"
