server:
  port: 9093
spring:
  application:
    name: video-service

  data:
    mongodb:
      host: localhost
      port: 27018
      database: videodb
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
      circuitbreaker:
        resilience4j:
          enabled: true


      
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
  instance:
       ip-address: 127.0.0.1
       preferIpAddress: true
       hostname: localhost
      

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
      
      
info:
  app:
    name: "video-service-from-git-server-latest"
    description:  "This is video service"
    version: "1.2"

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 1000
    instances:
          myVideoServiceCircuitBreaker:
            base-config: default
